### ISSUE TITLE
Menu doesn't work

### ISSUE THREAD

**Issue by ShadyThGod** [AlexTorresSk/custom-electron-titlebar#1]
Really loved this project, exactly what I needed. However there is one big issue that is the Menu. When the `menu` option is not specified in the renderer file, it doesn't show any menu. Also, when manually specifying the option using a menu template, the whole titlebar goes blank/white. Please fix.

**Comment by ShadyThGod** [comment]
Using `remote.Menu.buildFromTemplate(template)` seemed to work for me

**Comment by ShadyThGod** [comment]
Just realized however, the menu feature doesn't work fully. It just displays the top menu items and none of the sub-menu items.

**Comment by ShadyThGod** [comment]
Menu feature doesn't work fully. It just displays the top-most items in the menu without any personality like submenus, accelerators or click events.

**Comment by AlexTorresSk** [comment]
Hi @ShadyThGod.

The menu option was in development, but from version 2.0.0 it is partially functioning.

**Comment by Pritep** [comment]
en el método de [`updateMenu`](https://github.com/AlexTorresSk/custom-electron-titlebar/blob/master/README.md#update-menu) dice: "to create the menu use remote.Menu and remote.MenuItem" pero de donde se saca "remote", porque electron/remote esta "deprecated". Por favor explicar
