### ISSUE TITLE
Uncaught Error: Cannot find module 'custom-electron-titlebar' - using vue and electron compiled for windows

### ISSUE THREAD

**Issue by thekeithwaters** [AlexTorresSk/custom-electron-titlebar#100]
custom-electron-titlebar is not found using require / window.require from renderer process using Vue

In index.vue:
`const customTitlebar = window.require('custom-electron-titlebar')`
or
`const customTitlebar = require('custom-electron-titlebar')`
even though the previous line works 100%:
`const ipcRenderer = window.require('electron').ipcRenderer`

**Expected behavior**
App should work 

**Screenshots**
![image](https://user-images.githubusercontent.com/7078823/96139552-41e66680-0eff-11eb-926f-c7ac39b138f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Electron version 10.1.3
 - Node Version 12.16.3

I have searched high and low and tried everything I could find.
Your help would be greatly appreciated, please!

**Comment by thekeithwaters** [comment]
I tried 
`import { Titlebar, Color } from 'custom-electron-titlebar';`
but then I get 
` Uncaught TypeError: r.existsSync is not a function`
![image](https://user-images.githubusercontent.com/7078823/96142005-deaa0380-0f01-11eb-936c-518687b6795f.png)

**Comment by AlexTorresSk** [comment]
Title bar implementation works if the code is added in **preload.js** file

For more information check the following [link](https://github.com/AlexTorresSk/custom-electron-titlebar/blob/master/example/preload.js)

**Comment by thekeithwaters** [comment]
Thanks so much for this.      I've managed to get it working.

For the sake of those searching for this issue in the future, you will need to add a preload line to your webpack config (for me, it's vue.config.js) like this:
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js' 
    }
  }
}
```
It was also not obvious in the docs how to replace the menu options -  it turns out that the custom menu cleverly copies the "normal" menu options (the ones you'll be hiding) - so changing the normal menu options like this:

```
  import {   Menu  } from 'electron'
  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
```

will do the trick.

**Comment by peepopoggers** [comment]
Having the same issue, however the solution did not work. I am using a preload file with the config recommended, however nothing seems to happen.

**Comment by peepopoggers** [comment]
i am using vue too.
