### ISSUE TITLE
Change iconsTheme based on platform

### ISSUE THREAD

**Issue by Simbaclaws** [AlexTorresSk/custom-electron-titlebar#102]
Hi there,

Is it possible to change the window titlebar's iconTheme to that of the current platform?

For example:
When I'm on windows, the desktop app should show windows close, minimize and maximize buttons.

When I'm on mac OS, the desktop app should show mac OS close, minimize and maximize buttons.

When I'm on linux however, I would like to use the default titlebar that the user has specified for their window manager (Or preferably only the close minimize and maximize buttons). Linux users tend to have their own themes applied for their system, I want my app to reflect that.

How can I accomplish something like this?

**Comment by Simbaclaws** [comment]
Apparently this already works for windows and macOS,
I've successfully been able to get correct title bar buttons on both windows and macOS.
The only one not changing depending on the title of the current theme is linux. Currently it displays windows buttons on a linux distro.

**Comment by AlexTorresSk** [comment]
Hi!

This you request is not possible to do at the moment. I will leave it open to add in a future version if possible.
