### ISSUE TITLE
Could you please, please provide an example that works with Angular?

### ISSUE THREAD

**Issue by WilldelaVega777** [AlexTorresSk/custom-electron-titlebar#103]
**Describe the bug**
Doesn't seem to work with Angular 10

I followed all steps in the README.md

**To Reproduce**
1. Created the renderer.js file, put it in assets/js within my src folder
2. Called it from index.html, 
3. added code: 
```
const customTitlebar = require('custom-electron-titlebar');

new customTitlebar.Titlebar({
	backgroundColor: customTitlebar.Color.fromHex('#273c75')
});

```
to renderer.js

4. Added:
```
    mainWindow = new BrowserWindow(
        {
            title           : 'CSG',
            width           : 1250,
            height          : 900,
            minWidth        : 1250,
            minHeight       : 900,
            titleBarStyle   : "hidden",
            frame           : false,
            icon            : (`${__dirname}\\dist\\client\\assets\\images\\favicon-32x32.png`.replace(/\\/g, '/')),
            darkTheme       : true,
            webPreferences  : {
                nodeIntegration   : true,
                enableRemoteModule: true
            }
        }
    );
```
to main.js

**Expected behavior**
It should show the title bar and menus defined in Electron, but 
if you compile with Electron, it doesn't work, it takes away the window border and menus, but no replacements are added.

Any ideas please???? 

 - OS: Windows 10
 - Electron version 10.x
 - Node Version 10.x

**Comment by bierzorutas** [comment]
+1, no way to let it work in angular 8 + electron + electron-builder ...
