### ISSUE TITLE
Menu for separate window - Multi window application - win.setMenu()

### ISSUE THREAD

**Issue by kanji-keraliya** [AlexTorresSk/custom-electron-titlebar#104]
Hi there,

We have a application that have multiple window. I have implemented custom title bar using this package. 
We have different menu for different window so we are using window.setMenu() for window base menu in Windows and Linux platform.

How we can use window menu for this package?

Thanks in advance

**Comment by ericblade** [comment]
You can specify a different menu to use at Titlebar creation with the menu parameter
