### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by niwa01** [AlexTorresSk/custom-electron-titlebar#105]
When I start my electron app (`npx electron main.js`), on [this line](https://github.com/AlexTorresSk/custom-electron-titlebar/blob/master/src/browser/browser.ts#L139), i have this error.
Electronjs version: `v10.1.4`
Code:
```js
const { app, BrowserWindow } = require("electron");
const customTitlebar = require("custom-electron-titlebar");

function createWindow(){

  const window = new BrowserWindow({
    width: 1280,
    height: 720,
    resizable: false,
    titleBarStyle: "hidden",
    frame: false,
    webPreferences: {
      nodeIntegration: true,
    },
  });
  
  new customTitlebar.Titlebar({
    backgroundColor: customTitlebar.Color.fromHex("#444"),
  });

  window.loadFile("../public/index.html");
}
```

**Comment by leoata** [comment]
I'm using this with react and a workaround that I found was placing the Titlebar code inside of the react code instead of the electron. I'm not sure how this translates to your specific environment, but I would look to find a way to declare the Titlebar later in the initialization stages.

**Comment by ilikestohack** [comment]
I also have this issue and I am not using react and would not like to is there any other fix?

**Comment by Silventino** [comment]
Same issue here. @leoata, can you share how you did the workaround?

**Comment by SilentEsper** [comment]
I'm also experiencing the same issue

**Comment by SilentEsper** [comment]
I was able to fix this by including it after the react app render statement.
Just put it at the end of your index.html

**Comment by 0xdeafcafe** [comment]
It looks like you're instantiating TitleBar in the electron main process, rather than the renderer process (where it actually has access to the DOM). That is why it works when you added it into the `index.html` file.
