### ISSUE TITLE
icon definition in electron react

### ISSUE THREAD

**Issue by pierre-Fleury** [AlexTorresSk/custom-electron-titlebar#106]
Hello, 

I am currently using the custom-electron-titlebar in a electron react project, I tried to specify the icon like this : 

```js
window.addEventListener('DOMContentLoaded', () => {
  new customTitlebar.Titlebar({
    backgroundColor: customTitlebar.Color.fromHex('#2f3241'),
    icon: '/public/assets/squid.png',
    menu: null,
  });
```

But when i inspect the page of the electron app, the div rendering the icon has ````js background-url: 'http://localhost:3000/public/assets/squid.png'``` for csss property

Any idea why the icon property add the url of my localhost, or am I missing something about this ?

Thanks

**Comment by mpirescarvalho** [comment]
You have to import your image like you would do in a `<img />` tag

```
import icon from './assets/icon.png'

new Titlebar({
  backgroundColor: Color.fromHex('#333'),
  icon
})
```

**Comment by MaxiHafer** [comment]
The url of your localhost probably gets added because you are using a bundler - _inferring Webpack here_ - that serves your renderer through a local development server. If you build for production the files will be served from _file://_
