### ISSUE TITLE
CSS pseudo classes stopped working

### ISSUE THREAD

**Issue by Track-tor** [AlexTorresSk/custom-electron-titlebar#113]
Bug Description:
When I set a custom title bar on a window most CSS pseudo classes stop working.

1. Set any window with a custom title bar.
2. Assign a pseudo class style in CSS (like :hover).
3. Try to activate the event.
4. See that the style is not applied.

Expected behavior:
In the case of :hover the style should be applied when the mouse is hovering over the item, but the style is not being applied. This only happens when I include my 'titlebar.js' script inside a view of my project.

I haven't tested it, but I suspect that almost all mouse related events are not working properly.

Screenshots:
Button being hovered:
![image](https://user-images.githubusercontent.com/48454411/101978022-a63c5280-3c30-11eb-9fe9-cc06a821113d.png)

Expected style when hovered (applied by dev-console):
![image](https://user-images.githubusercontent.com/48454411/101978045-d1bf3d00-3c30-11eb-82c4-79cf052c1948.png)

titlebar.js:
![image](https://user-images.githubusercontent.com/48454411/101978081-18149c00-3c31-11eb-9a8f-bb3d3d94f830.png)

app.css:
![image](https://user-images.githubusercontent.com/48454411/101978114-6033be80-3c31-11eb-892b-71c2cef18be0.png)

main.html:
![image](https://user-images.githubusercontent.com/48454411/101978130-80fc1400-3c31-11eb-901b-f5a30ea911d8.png)

Desktop:
 - OS: Windows 8.1
 - Electron version: 11.1.0
 - Node Version: 14.15.1

**Comment by Track-tor** [comment]
After some tinkering I managed to find what was causing this issue: The '.container-after-titlebar' element was covering the whole window, basically taking a height of 100%. 

So, I basically 'solved' this problem by modifying the class and overwriting the height to be 0. IDK if this will mess with anything from the library, but for now it'll do.

**Comment by SeYoungKim** [comment]
I faced the same problem and found the reason why it happens:

<div class="container-after-titlebar"> element should have been loaded after "DOMContentLoaded" event.

take a look at this example:

https://github.com/AlexTorresSk/custom-electron-titlebar/blob/0e61605cae6b7721c04ef7f5ed68c9c64e1346e4/example/preload.js

Then, <div class="container-after-titlebar"> element can wrap the other elements in <body> element.

I think it would be great to explain(warn) this in the document.
