### ISSUE TITLE
Library does not work, unless you add: enableRemoteModule: true

### ISSUE THREAD

**Issue by Sten435** [AlexTorresSk/custom-electron-titlebar#115]
I saw that there was no indication in your readme, that **_enableRemoteModule_** needed to be enabled (set to true).

I discovered it and want to let you know.

If you don't use it you get an err when you try to launch your electron program.

This is the complete obj that --BrowserWindow-- needs to be: 

```js
BrowserWindow({
    width: 650,
    height: 500,
    titleBarStyle: "hidden",
    webPreferences: {
      enableRemoteModule: true
    }
  })
```

If you don't do that the ```    menu: electron_1.remote.Menu.getApplicationMenu(), ``` function will trow an err in titlebar:30, because it can't access .remote.

I hope you can mention this in your readme & on npm.js
Greetings Stan Persoons

**Comment by ericblade** [comment]
Might be worth making a modification that will not cause total failure without remote installed.  From a brief glance at the code, it looks like it would probably error even if you set menu to null, but I could be wrong about that.

**Comment by Sten435** [comment]
> Might be worth making a modification that will not cause total failure without remote installed. From a brief glance at the code, it looks like it would probably error even if you set menu to null, but I could be wrong about that.

I tested the code, that I showed and it worked perfectly.

**Comment by ericblade** [comment]
Yes, but there are reasons why remote module is not enabled by default, and IMO, it would be good to support running without it, even at reduced functionality.
