### ISSUE TITLE
Checkmark menu items do not work.

### ISSUE THREAD

**Issue by timlg07** [AlexTorresSk/custom-electron-titlebar#116]
**Description**
A menu item of the type "checkmark" does not behave like it does in electrons menu-bar. 
And when trying to build the expected behavior with the custom-electron-titlebar, it results in interference with electrons functionalities.

**To Reproduce**
Minimal example showing the issues is provided at the end.

**About rebuilding the expected behavior**
When a click-handler, to toggle the checkmark manually, is added (in the example provided as a comment), electrons default behaviour does not work anymore, because now the checkmark gets toggled twice.  
This may be ok in some use cases, because the default electron menu bar is hidden. But: The accelerators still seem to execute electrons default behavior.  
This results in the `click` function with the desired action being executed, but the checkmark still displaying its previous state.
So after a long time of debugging and searching for the problem, my current solution is to store the checkmark's state in the data model and manually set it from there, which I want to change as soon as possible. Also I am having issues when one checkmark influences a different checkmark: Because the submenus of submenus from the custom-electron-titlebar do not close after being clicked, a wrong state is shown, as only the clicked menu item gets updated and the other one changes its checkmark state only after the (sub)menu is being reopened.

**Expected behavior**
When clicking on a checkmark menu item, its `.checked` value should be inverted and the checkmark should appear or disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/33633786/103243417-16014b80-495a-11eb-9e37-e9c55c9af1e6.png)

**Desktop:**
 - OS: Windows 10
 - Electron version 1.7.16
 - Node Version 7.9.0
 - Custom-electron-titlebar version: 3.2.5

**renderer.js**
```js
const { Titlebar } = require('custom-electron-titlebar');
new Titlebar();
```
**main.js**
```js
const {app, BrowserWindow, Menu} = require('electron')
const path = require('path')
let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({webPreferences: {enableRemoteModule: true}})
  mainWindow.loadURL(path.join(__dirname, 'index.html'))
  mainWindow.on('closed', function () {mainWindow = null})
  Menu.setApplicationMenu(Menu.buildFromTemplate([{
    label: 'Menu',
    submenu: [{
      label: 'Toggle Me!',
      type: 'checkbox',
      // Toggle the checkmark manually:
      // click: o => o.checked = !o.checked,
      accelerator: "T"
    }]
  }]))
}

app.on('ready', createWindow)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
app.on('activate', () => {
  if (mainWindow === null) createWindow()
})
```

**Comment by Araxeus** [comment]
Dynamic check doesn't work either
IE: 
````
submenu: [
			{
				label: "Auto-update",
				type: "checkbox",
				checked: config.get("options.autoUpdates"),
				click: (item) => {
					config.set("options.autoUpdates", item.checked);
				},
			},
````

With electron native menu it will update the checkmark dynamically
but with this menu it wont.

I have a big menu built like the example above, is there any way to quickly fix it?
