### ISSUE TITLE
Submenu appears with a scrollbar

### ISSUE THREAD

**Issue by Kiyozz** [AlexTorresSk/custom-electron-titlebar#124]
**Describe the bug**

See the gif below

![Isw7jdT9vI](https://user-images.githubusercontent.com/12450333/105167925-a6761a80-5b19-11eb-8989-8fd555b82384.gif)

When you open a submenu, the menu appear at right but in a scrollbar (possible overflow problem)

**To Reproduce**
1. Disable all application css
2. Open a submenu

You can use my project [PCA - branch 79-titlebar](https://github.com/Kiyozz/papyrus-compiler-app/tree/79-titlebar) using pnpm, `pnpm i --shamefully-hoist`, `pnpm dev` (node@^14.15)

**Expected behavior**
Submenu appear next to the menu item

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Electron version 11.2.0
 - Node Version 12.18.4 (node version from electron 11.2.0)

**Comment by webbuildlucas** [comment]
Can confirm this bug, I fixed it temporarily by adding this line to a css file. As far as I can tell, it seems nothing else is affected by this change.
```css
  .menubar-menu-container{
    overflow-y: visible !important;
  }
```
