### ISSUE TITLE
close button is invalid

### ISSUE THREAD

**Issue by zhch-hong** [AlexTorresSk/custom-electron-titlebar#125]
click right-top close button and file submenu exit menu not every response

**Comment by timlg07** [comment]
Does this only occur when the developer tools are open, or always? What can we do to reproduce the issue you're facing?

**Comment by davidtavarez** [comment]
> Does this only occur when the developer tools are open, or always? What can we do to reproduce the issue you're facing?

only while the developer tools are open.

**Comment by timlg07** [comment]
I don't think that's a problem of this library. I believe it's part of the same electron issue that causes #130: https://github.com/electron/electron/issues/24910#issuecomment-743994256

I have seen in projects of others, that dev-tools are often closed manually. For example like this: https://github.com/aesqe/electron-image-viewer/blob/master/window.js#L79

**Comment by zhch-hong** [comment]
> > Does this only occur when the developer tools are open, or always? What can we do to reproduce the issue you're facing?
> 
> only while the developer tools are open.



> Does this only occur when the developer tools are open, or always? What can we do to reproduce the issue you're facing?

yes, only developer mode,production mode is valid
