### ISSUE TITLE
Take an (optional) argument to the window to set the titlebar to

### ISSUE THREAD

**Issue by ANF-Studios** [AlexTorresSk/custom-electron-titlebar#129]
When creating a new window, you can only set the titlebar to the main window which is not what you want to do in *some* cases.

It should be possible to supply the argument of the browser window to which window to set the titlebar to.

**Comment by ericblade** [comment]
? you create the titlebar inside the window that you are working with?

**Comment by ANF-Studios** [comment]
Well, yes, I want to assign the titlebar to my newly created window, however, it doesn't do that.

**Comment by ericblade** [comment]
The Titlebar is created inside the window renderer, not inside the node app.. so if you don't want to create the custom titlebar inside a particular window... just .. don't?  I don't understand what part you're not understanding.
