### ISSUE TITLE
Update the NPM Package to fix Fullscreen gap at the top of the page 

### ISSUE THREAD

**Issue by imdaveead** [AlexTorresSk/custom-electron-titlebar#13]
When in windowed mode, the titlebar works properly
![image](https://user-images.githubusercontent.com/24465214/52665859-a8b9ae00-2eda-11e9-8c2d-76c8976cc2fe.png)

Except when I press F11 to put the window into fullscreen (not maximized) mode, the titlebar disappears.
![image](https://user-images.githubusercontent.com/24465214/52665902-c1c25f00-2eda-11e9-8249-a74349238070.png)
> it's actually really hard to see it here, but theres a 30px tall white bar at the top of the screen

It seems like the code fixes this in `titlebar.ts`
```js
if (fullscreen) {
  hide(this.titlebar);
  this.container.style.top = '0px';
} else {
  show(this.titlebar);
  this.container.style.top = `${this.titlebar.getBoundingClientRect().bottom}px`;
}
```
...BUT in the latest npm build I find this compiled typescript instead, it's missing the `style.top` changes:
```js
if (!platform_1.isMacintosh) {
    if (fullscreen) {
        dom_1.hide(this.titlebar);
    }
    else {
        dom_1.show(this.titlebar);
    }
}
```

**Solution to this**: Update the npm package to a 3.1.0 or 3.0.1 or something.

**Comment by AlexTorresSk** [comment]
@imdaveead Check if this error is kept in the latest version, it has already been tested and everything works correctly.

If the error is maintained, please indicate in this same issue.
