### ISSUE TITLE
Extremely high close time.

### ISSUE THREAD

**Issue by timlg07** [AlexTorresSk/custom-electron-titlebar#130]
**Describe the bug**
When using the custom-electron-titlebar it takes much longer to close a window. In numbers: The time between the call of the close and closed events is at
- 10 - 15 ms when the frame is shown (`frame: true`)
- \> 500 ms when the frame is hidden (`frame: false`).

A possible "fix" would be to add
```js
win.on("close", win.destroy)
```
which drives down the close time to around 5 - 10 ms, but seems like a bad idea to use.

Note: When using the custom-electron-titlebar it makes a difference whether you use `frame: true` or `false`. This is not the case when the custom-electron-titlebar is not used: The close time with the hidden frame is still very low at around 10 ms.

**To Reproduce**
1. Clone [custom-electron-titlebar-minimal-example/tree/close-time-issue](https://github.com/timlg07/custom-electron-titlebar-minimal-example/tree/close-time-issue)
2. Install and start the application using npm
3. Close the window when using `frame: true` and `frame: false` or with and without using the custom-electron-titlebar and read the console output.

**Desktop:**
 - OS: Windows 10
 - Electron version 11.2.1
 - Node Version 12.18.3

**Comment by lociero** [comment]
@timlg07  This is a known [bug](https://github.com/electron/electron/issues/24910) of electron.

**Comment by timlg07** [comment]
@lociero Thanks for the link, I didn't knew this. Looks like the `beforeunload`-listener used by the titlebar of this library causes this behaviour. Do you happen to know a good work around?

**Comment by lociero** [comment]
@timlg07 I'm just sitting on 8.5.5 since I didn't find any workaround.

**Comment by timlg07** [comment]
@lociero hm that sucks... But thank you very much for the responses!

**Comment by ericblade** [comment]
I don't have any sort of problem like this, using 11

**Comment by timlg07** [comment]
@ericblade What times do you get when you try out the example I linked? And which version are you on?
