### ISSUE TITLE
menu roles not working (electron 11.2.3)

### ISSUE THREAD

**Issue by alex-bluetrain** [AlexTorresSk/custom-electron-titlebar#133]
The built in roles from electron Menu don't work when clicked through the custom-electron-titlebar, but they do on the native electron Menu.

I've tried reload, forceReload, zoomIn, zoomOut, copy, selectAll, quit, about
no roles seem to work at all on custom-electron-titlebar

edit: if I manually set a click() event on the menuItem, that works fine, it's just the roles that have trouble.

 - OS:  Windows 10 64bits
 - Electron v11.2.3
 - Node v10.23.0

**Comment by timlg07** [comment]
Yes, I also noticed this. Which version of the custom-electron-titlebar are you using? I think it's working fine for `version 3.2.5`, but does not for later versions.

**Comment by alex-bluetrain** [comment]
> 
> 
> Yes, I also noticed this. Which version of the custom-electron-titlebar are you using? I think it's working fine for `version 3.2.5`, but does not for later versions.

custom-electron-titlebar@3.2.6
I downgraded to 3.2.5 and it works fine! thanks for the hint

**Comment by pkkulhari** [comment]
> > Yes, I also noticed this. Which version of the custom-electron-titlebar are you using? I think it's working fine for `version 3.2.5`, but does not for later versions.
> 
> custom-electron-titlebar@3.2.6
> I downgraded to 3.2.5 and it works fine! thanks for the hint

Yes, I works with custom-electron-titlebar@3.2.5, but not all menu roles.

**Comment by Araxeus** [comment]
Would be nice to debug this, but its proving really difficult when I can't easily compare 3.2.5 and 3.2.6 since repo is outdated..
