### ISSUE TITLE
Bar doesn't load!

### ISSUE THREAD

**Issue by Minecodes** [AlexTorresSk/custom-electron-titlebar#134]
On my project isn't the bar working, that's in browser and in electron itself.
When i use it in my electron file it gives me only errors and in the browser it doesn't starts.

**Comment by timlg07** [comment]
Hey there :) if you want to get help fixing these errors, please provide more details.

Anyways it may be a good idea if you check out a simple example of a functioning electron app using this library first. You can have a look at this example I created for exactly that purpose: [custom-electron-titlebar-minimal-example](https://github.com/timlg07/custom-electron-titlebar-minimal-example).  
You can even use it as a template for your own repository and start implementing right away. 

If the given example does not work for you, please come back with the actual error messages and some detail about what OS and what node/electron versions you are using.
