### ISSUE TITLE
Custom Titlebar does not appear

### ISSUE THREAD

**Issue by AadiSahni** [AlexTorresSk/custom-electron-titlebar#138]
**Describe the bug**
The custom titlebar does not appear

**To Reproduce**
1. Main.js
`const electron =  require('electron')
const url = require('url')
const path = require('path')

const {app, BrowserWindow, Menu} = electron;
let mainWindow;

// Listen for app to be ready
app.on('ready', function(){
  // create new window
  var mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    frame: false,
    webPreferences: {
      nodeIntegration: true
    }
  });
  mainWindow.loadFile("index.html")
  });`

2. index.html
    <head>
        <title>Notes</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <script>
            const customTitlebar = require('custom-electron-titlebar');

            new customTitlebar.Titlebar({
            backgroundColor: customTitlebar.Color.fromHex('#000000')
            });
        </script>

        <nav class="cyan">
            <div>            
                <a class="brand-logo center"; style="font-family: Roboto; font-weight: bold; font-size: 32px;">
                    Notes
                </a>
                </nav>
            </div>
        </nav>
        <input>
     </body>
3. See error

**Expected behavior**
The custom titlebar should appear

**Desktop:**
 - OS: Windows 10 Pro 20H2 OS Build 19043.804
 - Electron version: v11.2.3
 - Node Version: v14.15.5

**Comment by timlg07** [comment]
You are missing the `enableRemoteModule: true` in your webPreferences. 

I won't explain more about it, because there are already a bunch of issues about exactly this topic. For example, you can have a look at #101, #115 or #126

**Comment by AadiSahni** [comment]
> You are missing the `enableRemoteModule: true` in your webPreferences.
> 
> I won't explain more about it, because there are already a bunch of issues about exactly this topic. For example, you can have a look at #101, #115 or #126

Thank you timlg07, that fixed the problem
