### ISSUE TITLE
Cannot read property 'Menu' of undefined

### ISSUE THREAD

**Issue by Spyynz** [AlexTorresSk/custom-electron-titlebar#140]
I get an error every single time I try to use this even when I follow tutorials. I have done step-by-step tutorials, read docs, etc. and it still shows this error. What do I do??? Is this an issue with this package?

**Comment by ericblade** [comment]
enable the remote module?

**Comment by Spyynz** [comment]
yes but I get the same error except instead of 'Menu' it's 'getElementByClass'

**Comment by timlg07** [comment]
> Is this an issue with this package?  

No, it's not.

Can you share a bit of what you've tried so far?  
And can you test this simple example ([custom-electron-titlebar-minimal-example](https://github.com/timlg07/custom-electron-titlebar-minimal-example)) and see if it works for you?

**Comment by ericblade** [comment]
fwiw, use with remoteModuleEnabled: false, requires some rearchitecture, probably https://github.com/AlexTorresSk/custom-electron-titlebar/issues/136

**Comment by ngudbhav** [comment]
> yes but I get the same error except instead of 'Menu' it's 'getElementByClass'

I got it working by using
```
window.addEventListener('DOMContentLoaded', () => {
  new customTitleBar.Titlebar()
});
```
