### ISSUE TITLE
Title isn't in the perfect center

### ISSUE THREAD

**Issue by NicoEschner** [AlexTorresSk/custom-electron-titlebar#144]
On the[ image here](https://i.imgur.com/MGv22SD.png) you can see that the title isn't perfect in the center of the bar.

Is it possible to display it in the very center?

**Comment by erikian** [comment]
Same issue here. Looks like it's centered considering only the available space, not the total window width.
![image](https://user-images.githubusercontent.com/19478575/115039206-9ff00880-9ea6-11eb-883c-63ad42c805a5.png)

**Comment by AlexTorresSk** [comment]
In beta 4.0.0 it was fixed
