### ISSUE TITLE
this is no work in mac os 10.15.7

### ISSUE THREAD

**Issue by samping** [AlexTorresSk/custom-electron-titlebar#145]
**Desktop (please complete the following information):**
 - OS: mac os 10.15.7
 - Electron version 12.0.1
 - Node Version 3.2.6

can not work in mac

**Comment by tarik56** [comment]
Hello, try using Electron version `"^9.0.0"` in your package.json, idk why but all versions above seem to not support the custom title bar.

**Comment by ericblade** [comment]
works fine up to 12 with me

**Comment by Araxeus** [comment]
Can confirm that it doesn't work with electron 11 and atleast *some* versions of macOS

**Comment by jharrels** [comment]
I can also confirm Electron 12.0.1 and MacOS 10.15.7 does not show the traffic signals for me. Making a frameless window without the custom titlebar package is also not showing the traffic lights like it used to, so some behavior may have changed elsewhere.

**Comment by jharrels** [comment]
I see what's going on here. You must add both titleBarStyle and frame BrowserWindow options in order for the Mac traffic lights to appear. titleBarStyle has no effect on Windows/Linux, but on the Mac, it causes the traffic lights to show.

`    titleBarStyle: "hiddenInset",
    frame: false,`

**Comment by Araxeus** [comment]
@jharrels what about the custom menu? does it work for you on mac?

**Comment by jharrels** [comment]
@Araxeus No, the custom menu does not show on the Mac. Works fine on Windows and Linux using the same code.

**Comment by wizzle-discord** [comment]
Hey guys, any update on this? Just trying to get it working on Catalina. I was on electron 11.0.2 but have tried 9.0.0 and no luck. Works fine on windows. I've followed the example code as well. Has anyone got it working?

**Comment by jharrels** [comment]
@wizzle-discord I finally gave up on it and moved to completely menu-less app, still using electron-custom-titlebar for the titlebar, however.

![Capture](https://user-images.githubusercontent.com/15329651/120893482-913dec00-c5e1-11eb-94af-add4aeddbd79.PNG)

**Comment by AlexTorresSk** [comment]
> @Araxeus No, the custom menu does not show on the Mac. Works fine on Windows and Linux using the same code.
> 
> ![mac](https://user-images.githubusercontent.com/15329651/118396437-895fdd00-b61d-11eb-8985-36e2852813f5.png)
> ![windows](https://user-images.githubusercontent.com/15329651/118396440-8cf36400-b61d-11eb-8a83-0a65683922ae.png)
> 

The custom menu is not displayed on Mac because on Mac the menu already appears in the upper left, next to the apple logo. This project is made to make that happen.

**Comment by ArsenicBismuth** [comment]
@AlexTorresDev Is it possible to override this behavior for macOS and keep showing the HTML-based menu? Imperfection is fine since I can fine-tune the layout in CSS.

Motive: I use this library to work around the fact that macOS hides app menu if we disable dock icon.
