### ISSUE TITLE
Please update NPM package

### ISSUE THREAD

**Issue by quantumdot** [AlexTorresSk/custom-electron-titlebar#161]
**Describe the bug**
Updated to electron 13.1.6, and a few problems are reported which stem from this module:

- NPM warns `custom-electron-titlebar@3.2.7 requires a peer of electron@^10.0.0 || ^11.0.0 || ^12.0.0 but none is installed. You must install peer dependencies yourself.`
- Upon loading of the application, receive an uncaught exception: `Uncaught TypeError: Cannot read property 'Menu' of undefined` in titlebar.js line 31. Relates to the use of deprecated electron.remote.

Both of these appear to have been fixed and merged into the master branch of this repo, but the package on NPM precedes these changes. 

**Expected behavior**
`custom-electron-titlebar` to work with electron 13.x

**Desktop (please complete the following information):**
 - OS: Windows
 - Electron version 13.1.6
 - Node Version 14.17.3

**Comment by ngudbhav** [comment]
As a workaround, you can set `enableRemoteModule: true` in BrowserWindow constuctor
