### ISSUE TITLE
Doesn't work with electron v16.0.0

### ISSUE THREAD

**Issue by Akyllyde** [AlexTorresSk/custom-electron-titlebar#165]
**Describe the bug**
Executing `npm install custom-electron-titlebar` shows this error 
```
Could not resolve dependency:
peer electron@"^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0" from custom-electron-titlebar@3.2.9 
node_modules/custom-electron-titlebar
custom-electron-titlebar@"*" from the root project
```

**Desktop:**
 - OS: Windows
 - Electron version: v16.0.5
 - Node Version: v16.13.1

**Comment by bierzorutas** [comment]
For me is not working, but not errors are present so maybe that´s the reason... thanks

**Comment by ericblade** [comment]
I'm not sure this can be fixed without major surgery, a few electron versions ago deprecated and probably removed in the interim, some of the architecture here. :|

**Comment by bierzorutas** [comment]
Hi @ericblade 
I give a quick update, at least in my case.
After many hours, I made it work.. Following the steps given in the README.md is not enough, I need in my case for example to call Remote.initialize() in main thread, and also in my specific case, as I have a splash loading screen, I need to specify to which window is applied, using Remote.enable(win.webContents).

Another issue I had was when going to FullScreen (F11 in windows), for me was not working, it hidde the min/max/close button but the topBar was pressent, so I need to add my own code to dispose() title bar and recreate in the preload.js file...

In MacOS is not working nothing, but this I am not sure if is expected or not..

**Comment by DerGoogler** [comment]
use `-f`

**Comment by Akyllyde** [comment]
> use `-f`
@DerGoogler forcing an install isn't good practice but I did that, and still doesn't work. I have made my own custom titlebar using IPCommunication

**Comment by froschi123** [comment]
Will that issue be fixed in the next version?

**Comment by AlexTorresSk** [comment]
> Will that issue be fixed in the next version?

In 4.0.0 was fixed
