### ISSUE TITLE
Windows 11 compatibility ?

### ISSUE THREAD

**Issue by bierzorutas** [AlexTorresSk/custom-electron-titlebar#166]
Electron app with custom-electron-titlebar is not showing the titlebar.
Has anyone tested it in Windows 11 and could confirm works/not ?

Thanks for the module @AlexTorresSk  !!

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Electron version 16.0.4
 - Node Version 14.17.5

**Comment by AlexTorresSk** [comment]
You can indicate how you are implementing the module.

I am currently using Windows 11 with the following versions and it works perfectly.

- Windows 11 Pro
- Electron 16.0.5
- Node 16.9.1

**Comment by bierzorutas** [comment]
Hi @AlexTorresSk ,
I did a code refactor in my project related with the topbar, and one of them solved this issue. I confirm is showing it fine in Windows 11, I close this.

Thanks
