### ISSUE TITLE
Titil bar not displaying electron 16.0.6

### ISSUE THREAD

**Issue by clovisamai** [AlexTorresSk/custom-electron-titlebar#167]
**Describe the bug**
Am new to electron. Not to be working when I place it in the renderer.js file

**Error**
`ReferenceError: require is not defined at renderer.js:8` - is the error when I open devtools

**Code**
`renderer.js`
```
const customTitlebar = require('custom-electron-titlebar');

new customTitlebar.Titlebar({
	backgroundColor: customTitlebar.Color.fromHex('#444')
});

titlebar.updateTitle('My Menu');

const menu = new Menu();
menu.append(new MenuItem({
	label: 'Item 1',
	submenu: [
		{
			label: 'Subitem 1',
			click: () => console.log('Click on subitem 1')
		},
		{
			type: 'separator'
		}
	]
}));

menu.append(new MenuItem({
	label: 'Item 2',
	submenu: [
		{
			label: 'Subitem checkbox',
			type: 'checkbox',
			checked: true
		},
		{
			type: 'separator'
		},
		{
			label: 'Subitem with submenu',
			submenu: [
				{
					label: 'Submenu &item 1',
					accelerator: 'Ctrl+T'
				}
			]
		}
	]
}));

titlebar.updateMenu(menu);
```
`index.html`
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <!-- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP -->
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
  <meta http-equiv="X-Content-Security-Policy" content="default-src 'self'; script-src 'self'">
  <title>Hello World!</title>
</head>

<body>
  <h1>Hello World!</h1>
  We are using Node.js <span id="node-version"></span>,
  Chromium <span id="chrome-version"></span>,
  and Electron <span id="electron-version"></span>.

  <script src="./renderer.js"></script>
</body>

</html>
```

**Platform:**
 - OS: [Windows]
 - Electron version [16.0.6]
 - Node Version [16.9.1]

**Comment by timlg07** [comment]
Use a preload script and require the library there. For a minimal setup example have a look at [custom-electron-titlebar-minimal-example](https://github.com/timlg07/custom-electron-titlebar-minimal-example)

Which version of the titlebar are you using? It may not be compatible with the electron version you are on. Also you might need to have a look at your webPreferences in the main process.

But this is not a bug of the titlebar, but an error with the usage of it, so it would be more fitting in a [discussion question](https://github.com/AlexTorresSk/custom-electron-titlebar/discussions)

**Comment by bierzorutas** [comment]
I can confirm it works in electron 16.0.6 in my project, so I also bet for what @timlg07  has said.

I have that portion of code: 
new customTitlebar.Titlebar....
in preload.js script also
