### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'members')

### ISSUE THREAD

**Issue by mcnamara-charles** [AlexTorresSk/custom-electron-titlebar#169]
So I'm new to electron, but not to NPM and certainly not to JavaScript. Initially when I was getting errors they were things like "require" is not defined. I read through the issues and updated this like so:

main.js
```
const createWindow = () => {
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        titleBarStyle: "hidden",
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
            enableRemoteModule: true // <-- as you can see I do have this already.
        },
    })

    ipcMain.handle('dark-mode:toggle', () => {
        if (nativeTheme.shouldUseDarkColors) {
          nativeTheme.themeSource = 'light'
        } else {
          nativeTheme.themeSource = 'dark'
        }
        return nativeTheme.shouldUseDarkColors
    })

    ipcMain.handle('dark-mode:system', () => {
        nativeTheme.themeSource = 'system'
    })

    win.loadFile('index.html')
}
```

I have the code in my preload script, after I removed it from my render script where it also wasn't working. Here is the important sections of my preload.js
```
const customTitlebar = require('custom-electron-titlebar');

window.addEventListener('DOMContentLoaded', () => {

    let MyTitleBar = new customTitlebar.Titlebar({
        backgroundColor: customTitlebar.Color.fromHex('#ffffff')
    });

    const replaceText = (selector, text) => {
        const element = document.getElementById(selector)
        if (element) element.innerText = text
    }
      for (const dependency of ['chrome', 'node', 'electron']) {
        replaceText(`${dependency}-version`, process.versions[dependency])
    }
})
```

The actual behavior is as follows:
1. I use `npm run start`
2. The app opens, completely white, then loads content after about 20 seconds with no titlebar present. 
3. Then I open developer tools and it gives me the error that is the title for this issue with lots of things having to do with remote.js, and a lot of yellow errors like DevTools failed to load source map: Could not parse content, Unexpected end of JSON input. It always points to files with formats following "foo".js.map

**Expected behavior**
I would expect a titlebar and a working app

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 21H2
 - Electron 16.0.7
 - Node Version: v14.18.1

**Comment by ShivamRawat0l** [comment]
Lol. Just getting this same error. Is it due to the version ?

**Comment by mcnamara-charles** [comment]
> 

No idea, first day using this. I suppose If i had to I could roll back my Electron version to check but that seems like more work than it's worth

**Comment by ShivamRawat0l** [comment]
Sitting on this issue for couple of hours. Tried different version. No fix. I am using react-electron boilerplate so tried using the javascript in react as well as in html. In html it is giving the error stated in the issue and in react it is saying fs and path is undefined.

**Comment by mcnamara-charles** [comment]
@ShivamRawat0l React likely has the same issue. fs and path don't work in react at this point so that's probably just covering the other issue

**Comment by ShivamRawat0l** [comment]
@mcnamara-charles Yeah so path is working just directly doing the npm --save i path . For fs inside the release/app/package.json adding the fs as dependacy will resolve it in electron-react-boilerplate. Now the issue is that fs value is undefined and the functions are not working. And adding the code inside the .ejs in the boilerplate doesn't shows the titlebar. :(

**Comment by AlexTorresSk** [comment]
> @AlexTorresSk Is this a bug I can resolve in Vanilla JavaScript? If not what's the timeline for this being fixed? I really want to use this plugin but I have this dev work due in a week so If I can't use this I'll want to build a custom solution.

Update to the latest version released yesterday and use the steps outlined in the [wiki](https://github.com/AlexTorresSk/custom-electron-titlebar/wiki). For latest version don't use `remoteModule`, use IPC

**Comment by mcnamara-charles** [comment]
@AlexTorresSk I'll go ahead and try this later and let you know how it goes. Thanks!

**Comment by ShivamRawat0l** [comment]
@AlexTorresSk @mcnamara-charles So now no error for me. 

```
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: __dirname + "/preload.js",
      nodeIntegration: true,
      contextIsolation: false,
    },
    titleBarStyle: "hidden",
  });
```

In preload.js is same as the example/preload.js in this repo. 
In renderer.js I am setting window.require = require for react js. 

So there is no error but I am not able to see the custom-titlebar. 

My end goal is to use it with ` frame : false, transparent: true `.  But for now titlebar not being displayed. Will play around for a while.

**Comment by mcnamara-charles** [comment]
@AlexTorresSk I had to add a menu apparently and in that file you have lines like `Menu.getApplicationMenu();` but Menu isn't defined in your example could you explain this?

**Comment by AlexTorresSk** [comment]
Explained on [wiki](https://github.com/AlexTorresSk/custom-electron-titlebar/wiki)
