### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by obsius** [AlexTorresSk/custom-electron-titlebar#19]
Fullscreen mode removes the titlebar which is to be expected, but because the menu is in the titlebar all of the menu items are unusable.

To fix this, perhaps the title bar should be preserved in fullscreen mode, and the minimize, maximize, exit buttons should transform into one exit and one un-fullscreen button.

**Comment by hatpick** [comment]
This is still incorrect for Mac. In Mac, menu doesn't sit on the title bar, so when in full screen mode, the entire title bar should disappear and the content after title bar needs to be adjusted.
