### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'toDataURL') at t.default._setupIcon

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [AlexTorresSk/custom-electron-titlebar#197]
**Describe the bug**
When using the package, it is firing the following error message on preload.ts:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toDataURL') at t.default._setupIcon
```

**To Reproduce**
1. Create a new electron + typescript project following this template: https://github.com/Deluze/electron-vue-template
2. Follow the instructions to setup custom-electron-titlebar
3. Add the following declaration to a .d.ts file to enable importing custom-electron-titlebar

```
declare module "custom-electron-titlebar/main" {
  import type cetMain from "custom-electron-titlebar/dist/main/main";
  
  export const setupTitlebar: typeof cetMain.setupTitlebar;
  export const attachTitlebarToWindow: typeof cetMain.attachTitlebarToWindow;
}
```

5. See the error in the console

**Expected behavior**
The expected behavior is to show the title bar

**Screenshots**
![image](https://user-images.githubusercontent.com/11933789/192885368-95fc1a8d-9fdb-4133-8014-417e37200993.png)

**Desktop:**
 - OS: Windows 11
 - Electron version: 20.1.0
 - Node Version: 16.13

**Comment by TiagoSilvaPereira** [comment]
@Muhammad-Taif-Khan no, but I discovered that it is not that hard to add a custom title bar to an electron app, so I decided to do it by myself: https://www.electronjs.org/docs/latest/tutorial/window-customization

**Comment by Arkellys** [comment]
The error comes from [this line](https://github.com/AlexTorresSk/custom-electron-titlebar/blob/1cdf68485b67edfaad92402b5c35f5466c24bd69/src/titlebar.ts#L205).
Setting the parameter `icon` fix the error, but I don't think it should be a mandatory option...

**Comment by Muhammad-Taif-Khan** [comment]
Yep, it should not be a mandatory one.

**Comment by AlexTorresSk** [comment]
Working on it

**Comment by AlexTorresSk** [comment]
> **Describe the bug**
> When using the package, it is firing the following error message on preload.ts:
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'toDataURL') at t.default._setupIcon
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Create a new electron + typescript project following this template: https://github.com/Deluze/electron-vue-template
> 2. Follow the instructions to setup custom-electron-titlebar
> 3. Add the following declaration to a .d.ts file to enable importing custom-electron-titlebar
> 
> ```
> declare module "custom-electron-titlebar/main" {
>   import type cetMain from "custom-electron-titlebar/dist/main/main";
>   
>   export const setupTitlebar: typeof cetMain.setupTitlebar;
>   export const attachTitlebarToWindow: typeof cetMain.attachTitlebarToWindow;
> }
> ```
> 
> 5. See the error in the console
> 
> **Expected behavior**
> The expected behavior is to show the title bar
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/11933789/192885368-95fc1a8d-9fdb-4133-8014-417e37200993.png)
> 
> **Desktop:**
>  - OS: Windows 11
>  - Electron version: 20.1.0
>  - Node Version: 16.13
> 

This bug was fixed in the clean code branch. In the next few weeks a beta will be released and in the next month the stable version. 🚀🚀
