### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by yomiAdenaike01** [AlexTorresSk/custom-electron-titlebar#20]
Running windows 10 currently no keyboard shortcuts are working.

**Comment by AlexTorresSk** [comment]
Are you sure you have an `accelerator` defined for each item of the menu that you want to access through the keyboard shortcut?

Example:

```js
new MenuItem({
  label: 'Print',
  accelerator: 'CmdOrCtrl+P',
  click: () => { console.log('time to print stuff') }
})
```

**Comment by janvorisek** [comment]
I can confirm keyboard shortcuts are working properly on Windows 10. Just make sure accelerators are set correctly as @AlexTorresSk stated.

**Comment by yomiAdenaike01** [comment]
Oh yeh they are i forgot to use Menu.setApplicationMenu() thank you !
