### ISSUE TITLE
Minimize, expand, and close options.

### ISSUE THREAD

**Issue by sharkmigue** [AlexTorresSk/custom-electron-titlebar#25]
This is not an issue, its more a question. I can't seem to find any documentation where I see how to set the minimize, expand, and close options. How can I set them.
This is my default title bar:
```
    new customTitlebar.Titlebar({
        backgroundColor: customTitlebar.Color.fromHex('#444'),
        minimizable: true,
        maximizable: true,
        closeable: true
    });
```

**Comment by AlexTorresSk** [comment]
In https://github.com/AlexTorresSk/custom-electron-titlebar#options are define these options.

Basically what it does is one of those properties that these naming is the following:

- `minimizable: boolean`
Enables or disables the option to minimize the window by clicking on the corresponding button in the title bar.
- `maximizable: boolean`
Enables or disables the option to maximize and un-maximize the window by clicking on the corresponding button in the title bar.
- `closeable: boolean`
Enables or disables the option of the close window by clicking on the corresponding button in the title bar.

**Note:** By default, these options are `true`.
