### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/css/titlebar.css'

### ISSUE THREAD

**Issue by richardliebmann** [AlexTorresSk/custom-electron-titlebar#3]
Platform: macOS

It works in electron start mode but not, when I build the app.

**Comment by richardliebmann** [comment]
On macOS I use following code (because, i will hide the menu and icon and use the top-bar only):
```            
window.titlebar = new Titlebar('#9c27b0', {
    icon: null,
    menu: null
});
```

On windows it works perfect! I have now comment out the line, which loads the style sheet and include it manually, witch works fine.

**Comment by AlexTorresSk** [comment]
This will be solved in the next version by loading the style using javascript, thus avoiding reading `css` files.

**Comment by AlexTorresSk** [comment]
Bug fixed on the last version
