### ISSUE TITLE
Error attempting to call function in renderer window that has been closed

### ISSUE THREAD

**Issue by hcphoon01** [AlexTorresSk/custom-electron-titlebar#32]
I have a head.html file which is imported into all my other html files, inside the head.html file is a script with the following code 
```
const customTitlebar = require('custom-electron-titlebar');

new customTitlebar.Titlebar({
    backgroundColor: customTitlebar.Color.fromHex('#262626')
});
```

Although whenever I interact with my application I get this error 

`Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Titlebar.registerListeners (D:\Projects\electron-app\node_modules\custom-electron-titlebar\lib\titlebar.js:50:28`

It only appears in the console however so does not actually affect my app but I want to know why it is erroring.

Thanks

**Comment by hcphoon01** [comment]
I'm now using create-react-app and I put the titlebar inside my index.html (which gets loaded with every page) and I still get the same error

**Comment by AlexTorresSk** [comment]
Please, attach a screenshot.

**Comment by hcphoon01** [comment]
A screenshot of?

**Comment by AlexTorresSk** [comment]
This error may be generated by trying to re-create the title bar, as this must be created only once. If you want the title bar to be kept on other pages you must delete it before moving on to another page using: [Dispose method](https://github.com/AlexTorresSk/custom-electron-titlebar#dispose).

**Comment by janvorisek** [comment]
This happens when using webpack-dev-server or similar tools. As the titlebar is a part of renderer code, it get hot-reloaded without calling the proper `dispose` function. You may need to call `dispose` method as Alex stated in some of the webpack-dev-server callbacks or on electron window close event.

**Comment by RHulshizer** [comment]
Hi. I get this same error, but I can assure you that my code only executes, as it is in Index.html:

const customTitlebar = require('custom-electron-titlebar');
        new customTitlebar.Titlebar({
            backgroundColor: customTitlebar.Color.fromHex('#444'),
            icon: './assets/icon.png'
        });

See screenshot
![error](https://user-images.githubusercontent.com/10155712/60997060-e56fc100-a323-11e9-8254-692a22e28b5b.png)

**Comment by Eisa01** [comment]
Same error, though my code executes once only as it is in index.html

**Comment by bala-veeravalli** [comment]
This is happening because the listeners registered on current browser window are no longer available when we load a different url. May be we can unregister these listeners when we dispose the titleBar to fix this.

**Comment by yafp** [comment]
Got the same issue, using version 3.1.0.

It happens i.e. when my app lost focus and then gets focus again.
Resulting output:

```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: titlebar.js:56:28
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: titlebar.js:56:28
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: titlebar.js:69:28
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: titlebar.js:69:28
```

**Comment by AlexTorresSk** [comment]
Can you attach your code?

**Comment by yafp** [comment]
@AlexTorresSk 
If i remember right the following commit in a fork of your repo solved the related issues for me:

https://github.com/panjiang/custom-electron-titlebar/commit/825bff6b15e9223c1160208847b4c5010610bcf7

Hope that helps

**Comment by jtvberg** [comment]
@AlexTorresSk 
I am having the same issue. Only one instance, it renders properly, default window actions still work. Custom menu items do not as I get the above error from registerListeners. Also comes up on unfocus/focus.
