### ISSUE TITLE
doesn't show accelerators for electron default items

### ISSUE THREAD

**Issue by arolson101** [AlexTorresSk/custom-electron-titlebar#38]
You can see in the screenshot, on windows the default electron items don't show the accelerators.  E.g. "Undo" should have "Ctrl+Z" next to it.

**Comment by AlexTorresSk** [comment]
Resolved partially on [9679adb3](https://github.com/AlexTorresSk/custom-electron-titlebar/commit/9679adb39e3a889e9384569b3e49b7a00bb7bf20)
