### ISSUE TITLE
Incorrectly localized accelerators

### ISSUE THREAD

**Issue by arolson101** [AlexTorresSk/custom-electron-titlebar#41]
I'm in en-us and it shows as "Ctrl+Mayus+I" instead of "Ctrl+Shift+I" for Toggle Developer Tools

related to #38

**Comment by davwheat** [comment]
This is still an issue...

**Comment by davwheat** [comment]
https://puu.sh/E1qRd/975c0891d7.png

**Comment by arolson101** [comment]
looks like it just hasn't been published on npm since the update.

**Comment by davwheat** [comment]
Yup. Looks like it: https://github.com/AlexTorresSk/custom-electron-titlebar/blob/7f76cbd2f46e36b9ddab6fd4bb006695013f5855/src/menu/menuitem.ts#L190

**Comment by AlexTorresSk** [comment]
You can use this with beta version 3.1.0-beta.0

 ```bash
npm i custom-electron-titlebar@beta
```
