### ISSUE TITLE
MenuItem "visible" property does not work

### ISSUE THREAD

**Issue by robgonnella** [AlexTorresSk/custom-electron-titlebar#45]
Electron allows you to set a "visible" prop on menu items that will hide and show the item accordingly, but this does not seem to work with this library.

**Comment by robgonnella** [comment]
Not sure if this is the right approach but I took a crack a addressing this issue. Tested in an app I've been working on and seemed to do the trick: https://github.com/AlexTorresSk/custom-electron-titlebar/pull/46

**Comment by AlexTorresSk** [comment]
Resolved on #46
