### ISSUE TITLE
overflow: hidden removes titlebar

### ISSUE THREAD

**Issue by ivanjeremic** [AlexTorresSk/custom-electron-titlebar#50]
When using the parameter overflow: hidden it removes the title bar completely, I don't even know why this titlebar-framework is adding a scrollbar, my app main.css has already overflow hidden but for some reason adding titlebar adds a overflow. I also tried to remove my own overflow: hidden and only use it inside the titlebar parameters to remove it, but it removes not only the overflow but also the whole custom-electron-titlebar.

It seems for me when looking at the scrollbar it adds exactly that much to scroll how much the height of the custom-electron-titlebar is so the CET itself is the reason I get a scrollbar I hope there is a fix for this.

**EDIT** I have found out that "custom-electron-titlebar" is breaking layouts that are made with CSS-Grid, here an simple grid you can add in Electron App to reproduce the bug [https://github.com/ireade/holy-grail-css-grid](https://github.com/ireade/holy-grail-css-grid)

**EDIT** When adding the parameter overflow: hidden as I said before the whole custom-electron-titlebar is removed but interesting is that the drag region works so I can drag around the area where the custom-electron-titlebar need to be normally.

**Comment by AlexTorresSk** [comment]
View #52
