### ISSUE TITLE
Terminal warnings on Windows 10

### ISSUE THREAD

**Issue by nickensoul** [AlexTorresSk/custom-electron-titlebar#55]
Using this package cause terminal warnings with following message:
```Function provided here: Titlebar.registerListeners (C:\path-to-project\node_modules\custom-electron-titlebar\lib\titlebar.js:56:28```

Environment:
Platform: `Windows 10 x64`;
Versions:
`electron: "^5.0.3"`
`custom-electron-titlebar: "^3.1.0"`

**Comment by AlexTorresSk** [comment]
Can you attach your code?

**Comment by cj3636** [comment]
Code for custom title bar:

`import { remote } from 'electron';

const customTitleBar = require('custom-electron-titlebar');

const menu = new remote.Menu();

const Config = require('electron-config');

const config = new Config();

const TryptorMainTitleBar = new customTitleBar.Titlebar({
  backgroundColor: customTitleBar.Color.fromHex('#23272a'),
  icon: './img/logo.png',
  overflow: 'hidden',
  shadow: true
});

menu.append(new remote.MenuItem({
  label: 'Home',
  click: () => goHome(),
  type: 'separator',
}));

menu.append(new remote.MenuItem({
  label: 'Panel',
  click: () => openPanel(),
  type: 'separator',
}));

if (config.get('devMode')) {
  menu.append(new remote.MenuItem({
    label: 'Debug',
    click: () => toggleDev(),
    type: 'separator',
  }));
}

function toggleDev() {
  if (remote.getCurrentWindow()
    .webContents
    .isDevToolsOpened()) {
    remote.getCurrentWindow()
      .webContents
      .closeDevTools();
  } else {
    remote.getCurrentWindow()
      .webContents
      .openDevTools();
  }
}

function refreshMenu() {
  TryptorMainTitleBar.dispose();
}

function goHome() {
  refreshMenu();
  remote.getCurrentWindow()
    .loadURL(`file://${__dirname}/index.html`);
}

function openPanel() {
  refreshMenu();
  remote.getCurrentWindow()
    .loadURL(`file://${__dirname}/panel.html`);
}

TryptorMainTitleBar.updateMenu(menu);
`
Error:
`Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Titlebar.registerListeners (C:\Users\USERNAME\Desktop\Tryptor\node_modules\custom-electron-titlebar\lib\titlebar.js:61:28
`

**Comment by cj3636** [comment]
Code:
```
import { remote } from 'electron';

const customTitleBar = require('custom-electron-titlebar');

const menu = new remote.Menu();

const Config = require('electron-config');

const config = new Config();

const TryptorMainTitleBar = new customTitleBar.Titlebar({
  backgroundColor: customTitleBar.Color.fromHex('#23272a'),
  icon: './img/logo.png',
  overflow: 'hidden',
  shadow: true
});

menu.append(new remote.MenuItem({
  label: 'Home',
  click: () => goHome(),
  type: 'separator',
}));

menu.append(new remote.MenuItem({
  label: 'Panel',
  click: () => openPanel(),
  type: 'separator',
}));

if (config.get('devMode')) {
  menu.append(new remote.MenuItem({
    label: 'Debug',
    click: () => toggleDev(),
    type: 'separator',
  }));
}

function toggleDev() {
  if (remote.getCurrentWindow()
    .webContents
    .isDevToolsOpened()) {
    remote.getCurrentWindow()
      .webContents
      .closeDevTools();
  } else {
    remote.getCurrentWindow()
      .webContents
      .openDevTools();
  }
}

function refreshMenu() {
  TryptorMainTitleBar.dispose();
}

function goHome() {
  refreshMenu();
  remote.getCurrentWindow()
    .loadURL(`file://${__dirname}/index.html`);
}

function openPanel() {
  refreshMenu();
  remote.getCurrentWindow()
    .loadURL(`file://${__dirname}/panel.html`);
}

TryptorMainTitleBar.updateMenu(menu);

```

Error:
```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Titlebar.registerListeners (C:\Users\USERNAME\bin\Tryptor\node_modules\custom-electron-titlebar\lib\titlebar.js:61:28
```

This occurs once a menu button has been used.

**Comment by AlexTorresSk** [comment]
You cannot change the window file that way, as the titlebar would have to be placed in each file.

I'll close this issue because the project functions as a title bar, to move through pages you have to create a container that changes dynamically when you press the menu. Type [VS Code](https://code.visualstudio.com/).

**Comment by cj3636** [comment]
> You cannot change the window file that way, as the titlebar would have to be placed in each file.
> 
> I'll close this issue because the project functions as a title bar, to move through pages you have to create a container that changes dynamically when you press the menu. Type [VS Code](https://code.visualstudio.com/).

Okay that makes sense, thank you for responding, but I don't understand what you mean by "Type VS Code"?
