### ISSUE TITLE
autoMenuHide doesnt reflect

### ISSUE THREAD

**Issue by pl4yradam** [AlexTorresSk/custom-electron-titlebar#56]
I have set my new browser window autoHideMenuBar: True
When I look a the titlebar generated from the package it doesn't reflect it.
Using the documentation to create new menus causes construct errors in angular 8

**Comment by AlexTorresSk** [comment]
Can you attach your code?

**Comment by AlexTorresSk** [comment]
Closed because the issue is not understood and no response was obtained.
