### ISSUE TITLE
Question: no longer an archived repo

### ISSUE THREAD

**Issue by yafp** [AlexTorresSk/custom-electron-titlebar#59]
Hey,

i noticed some month ago that this repository was archived and assumed it is no longer actively developed.

Therefor i switched to a fork of it.

Now i am realizing the project is no longer archived on github, does this mean you are back working on it?

**Comment by AlexTorresSk** [comment]
Hello. Yes, that's right. A while ago I archived the project because I did not intend to give it more support, but I noticed that it has had too much reception so I decided to support it again from now on.

**If you have new changes and want to join them would be wonderful.**

**Comment by yafp** [comment]
@AlexTorresSk Thanks for your answer. Thumbs up
