### ISSUE TITLE
Add support for updating itemBackgroundColor

### ISSUE THREAD

**Issue by yafp** [AlexTorresSk/custom-electron-titlebar#62]
Am i right that we can update the titlebar background color using 

`titlebar.updateBackground(new Color(new RGBA(0, 0, 0, .7)));`

but not the somehow related `itemBackgroundColor`?

**Background:**

I am using custom-electron-titlbar in an electron application which offers support for themes.
While switching themes i do as well adjust the background color of the titlebar. This is great - but the changing `itemBackgroundColor` as well would be perfect to match the style as good as possible.

**Comment by yafp** [comment]
@AlexTorresSk 
what do you think about that idea?
Worth thinking about it or should i just close the issue?

**Comment by AlexTorresSk** [comment]
I don't understand very well what you mean by that.

What you want is that you can color the background of each item. Well, ```itemBackgroundColor``` already exists, which is the color shown when the mouse is hover on the item.

**Comment by yafp** [comment]
Hey,

no i want to be able to set the hover color of menu items.
This would help adjusting the style after having changed the background color of the entire menu/titlebar.

Sorry if my first post was misleading

**Comment by AlexTorresSk** [comment]
@yafp - This will be added in the next release. Available January 30 🎉

**Comment by yafp** [comment]
@AlexTorresSk 
Thanks for your work on this.

I just updated to 3.2.2 and tried running this command:

`myTitlebar.updateItemBGColor(customTitlebar.Color.fromHex(newColor))`

where newColor has the value `#FFFFFF`

This results in the following output:

```
Unhandled Error
TypeError: myTitlebar.updateItemBGColor is not a function
    at titlebarUpdateItemBackgroundOnHover...
```

any idea what i am doing wrong?

**Comment by AlexTorresSk** [comment]
Opps! This error occurs because I forgot to build the project after i have completed the upgrade. 🤦‍♂ 

Corrected in the new version 3.2.2-hotfix62

I apologize.

**Comment by yafp** [comment]
alright, that explains everything ;)

**Comment by yafp** [comment]
@AlexTorresSk 
works with the hotfix

**Comment by yafp** [comment]
@AlexTorresSk 
just for your information.

The command `updateItemBGColor` does in fact work if i am running `3.2.2-hotfix62`, while it doesn't with `3.2.2`

What might cause issue for some currently messing around with your package is the following.
Running `npm-check -s` tells me the following

```
custom-electron-titlebar   😍  UPDATE!   Your local install is out of date. https://github.com/AlexTorresSk/custom-electron-titlebar#readme
                                        npm install --save custom-electron-titlebar@3.2.2 to go from 3.2.2-hotfix62 to 3.2.2
```

So it might look for some developers that 3.2.2 is > 3.2.2-hotfix62.

Not a big issue - i just stumbled upon it.

**Comment by yafp** [comment]
Just to show the result

![custom-electron-titlebar](https://user-images.githubusercontent.com/67605/73918023-fdf78800-48c0-11ea-9a34-e69245ad8078.png)

Thanks once again
