### ISSUE TITLE
[Question] background color on-focus vs non-focus

### ISSUE THREAD

**Issue by yafp** [AlexTorresSk/custom-electron-titlebar#64]
I am realizing that the titlebar background color slightly changes if the application has focus or not.

Is that a function of custom-electron-titlebar or is that done by my desktop environment?

**on-focus:**

![titlebar_focus](https://user-images.githubusercontent.com/67605/71963724-8d474800-31fc-11ea-9eec-24a7d657460b.png)

**non-focus:**
![titlebar_non_focus](https://user-images.githubusercontent.com/67605/71963738-91736580-31fc-11ea-9d23-65fa252e2c9e.png)

**Comment by AlexTorresSk** [comment]
@yafp This is done using the custom electron title bar

**Comment by yafp** [comment]
@AlexTorresSk 
thanks for pointing that out.

Is that configurable?

**Comment by AlexTorresSk** [comment]
@yafp 

No. The title bar becomes color opacity when the window is unfocus. If this were customizable, it would cause the blur design to be lost.

**I can adjust the opacity by a lighter one**

**Comment by yafp** [comment]
> I can adjust the opacity by a lighter one

No, i'm fine with it.

I was more or less hoping to have a setting like 

`unfocusEffect: true/false`

But this is far away from important.

**Comment by duhruh** [comment]
+1 to making this configurable

**Comment by AlexTorresSk** [comment]
@yafp - This will be added in the next release. Available January 30 🎉

**Comment by AlexTorresSk** [comment]
@yafp 

In the documentation *(README.MD file)* **I forgot to place this attribute**.

Use ```unfocusEffect:``` ```true``` or ```false``` to trigger the effect or not 🎉
