### ISSUE TITLE
[Question] Menu on first load

### ISSUE THREAD

**Issue by jtvberg** [AlexTorresSk/custom-electron-titlebar#65]
Hi Alex, 
I am really liking the custom menu! I am, however, having an odd issue. Your latest commit fixed some of my issues but I still have 2:
1. The first time the browser loads I get a default menu. The custom menu and its items do not show up. They then become visible when I reload it.
2. Once my menus show up, the items that I added give me an error (though the stock, role-based menu items still work):

> Attempting to call a function in a renderer window that has been closed or released.
> Function provided here: undefined

Is this an artifact of reloading? If so, I can work around that but I am not sure why my menus don't show up in the initial load.

Any advice would be appreciated.
Thank you!

**Comment by yafp** [comment]
could you show some example code?

**Comment by jtvberg** [comment]
Hi Fidel,
Assume use of the electron quick-start file layout and nomenclature.
In my renderer.js I have this:
```
const customTitlebar = require('custom-electron-titlebar')
const ctb = new customTitlebar.Titlebar({
  backgroundColor: customTitlebar.Color.fromHex('#34495e'),
  icon: './res/icon.png'
})

window.doSomething = () => {
  alert('didSomething')
}
```

In my menu.js I have this:
```
const { remote, shell } = require('electron')
const template = [
  {
    label: 'Test',
    submenu: [
      {
        label: 'Something',
        accelerator: 'CmdOrCtrl+S',
        click () { window.doSomething() }
      }
    ]
  },
  {
    role: 'editMenu'
  },
  {
    role: 'windowMenu'
  },
  {
    role: 'help',
    submenu: [
      {
        label: 'Toggle Dev Tools',
        role: 'toggleDevTools'
      }
    ]
  }
]

const menu = remote.Menu.buildFromTemplate(template)
remote.Menu.setApplicationMenu(menu)
```
The 'Test' menu won't show up on initial load. Even if I put the instantiation of the 'ctb' in the index.html.
If I refresh the window, it shows up but the submenu items under 'Test' produce the error.
All the other role-based menu items work as intended as do the accelerators for the custom items.

I should note that I am using bootstrap.

**Comment by AlexTorresSk** [comment]
What file are you loading first?

**Comment by jtvberg** [comment]
Sorry, was on a trip...
main.js instantiates the browser window and loads index.html which references renderer.js and menu.js in a script tag in this order:
```
<script type="text/javascript" src="./renderer.js"></script>
<script type="text/javascript" src="./menu.js"></script>
```

**Comment by jtvberg** [comment]
I wrote the above and then it clicked. When I move the require for the menu to the renderer, it works... which makes sense given where I am creating the CTB. Should have talked to the rubber ducky a bit more. 

Thanks for the help.

**Comment by AlexTorresSk** [comment]
There should always be renderer.js or the file where the custom title bar is, at the last position.
