### ISSUE TITLE
TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by march1993** [AlexTorresSk/custom-electron-titlebar#68]
see https://github.com/electron/electron/issues/7300

Changing all three `const electron_1 = require("electron");` to `const electron_1 = window.require("electron");` solves the problem.

**Comment by Medivhus** [comment]
Same issue here, changing the require did not fix the problem tho

**Comment by nihartrivedi810** [comment]
Add the following to your `preload.js`
```
window.CustomElectronTitlebar = require('custom-electron-titlebar');
```

And in the renderer process, you can now do:

```
const titleBar = new window.CustomElectronTitlebar.Titlebar({...options})
```
