### ISSUE TITLE
Maybe Bug: TitleBar causes scroll-bar.

### ISSUE THREAD

**Issue by MairwunNx** [AlexTorresSk/custom-electron-titlebar#7]
After adding code to html, my application start with scroll-bar, it not cool.

![image](https://user-images.githubusercontent.com/39625750/51368971-a5f9b200-1b02-11e9-9576-b69f44716008.png)

```
  <body>
    <div id="app"></div>

    <script>
      const customTitlebar = require('custom-electron-titlebar')

      new customTitlebar.Titlebar('#303030', {
        icon: './favicon.svg',
        iconsStyle: customTitlebar.Themebar.win,
        menu: null
      })
    </script>
  </body>
```

**Comment by AlexTorresSk** [comment]
Does this appear only when it has content in the body or at all times?

**Comment by MairwunNx** [comment]
@AlexTorresSk all times when applied custom bar.

But, it not critical bug, it easy can be fixed as 

```
html {
    min-height: 105%;
}
```
