### ISSUE TITLE
Changing the titlebar background color from css

### ISSUE THREAD

**Issue by Collatz124** [AlexTorresSk/custom-electron-titlebar#71]
Hey, is it in any way possible to change the title bars background color? I cannot get it to work through the .titebar  tag

**Comment by AlexTorresSk** [comment]
You can change the titlebar color using ```.updateBackground``` method from titlebar

**Comment by Collatz124** [comment]
But how can i update the background color, from a button on the menu in the titlebar? you have to define a click function, however titlebar isn't defined yet
