### ISSUE TITLE
Zoom in/out does not work

### ISSUE THREAD

**Issue by loblab** [AlexTorresSk/custom-electron-titlebar#72]
Node.js 12.8.1, Chromium 78.0.3904.130, and Electron 7.1.12.

Just run the example, click menu items "Zoom In/Out", "Actual Size", no response.
However, hot keys work. (Full screen menu works)

![image](https://user-images.githubusercontent.com/11693722/74834046-9d069000-5355-11ea-8743-b6c6542be547.png)

Enable both system default menu bar & this custom title bar in my app.  Zoom in... in system menu works, while custom bar not.

![image](https://user-images.githubusercontent.com/11693722/74834352-37ff6a00-5356-11ea-8487-928cb3087d75.png)

**Comment by ganeshh123** [comment]
None of the edit functions work for me, as well.
