### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by Holo-SW** [AlexTorresSk/custom-electron-titlebar#74]
after putting: `const customTitlebar = require('custom-electron-titlebar');`

I have : 

> App threw an error during load
> ReferenceError: navigator is not defined
>     at Object.<anonymous> (D:\Donnees\Desktop\electron-projet\node_modules\custom-electron-titlebar\lib\browser\browser.js:130:19)
>     at Module._compile (internal/modules/cjs/loader.js:968:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
>     at Module.load (internal/modules/cjs/loader.js:816:32)
>     at Module._load (internal/modules/cjs/loader.js:728:14)
>     at Module._load (electron/js2c/asar.js:717:26)
>     at Function.Module._load (electron/js2c/asar.js:717:26)
>     at Module.require (internal/modules/cjs/loader.js:853:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (D:\Donnees\Desktop\electron-projet\node_modules\custom-electron-titlebar\lib\common\dom.js:7:17)

**Comment by whizyrel** [comment]
Where did you put that piece of code, in the renderer file? It's supposed to be in another script that has access to the dom and not your main process file.
Like the script referenced in the src of an HTML file. If you have something like:
homepage.html and a homepage.js script linked in that html file,
Put that piece of code inside and and it would work just fine

**Comment by whizyrel** [comment]
> after putting: `const customTitlebar = require('custom-electron-titlebar');`
> 
> I have :
> 
> > App threw an error during load
> > ReferenceError: navigator is not defined
> > at Object. (D:\Donnees\Desktop\electron-projet\node_modules\custom-electron-titlebar\lib\browser\browser.js:130:19)
> > at Module._compile (internal/modules/cjs/loader.js:968:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
> > at Module.load (internal/modules/cjs/loader.js:816:32)
> > at Module._load (internal/modules/cjs/loader.js:728:14)
> > at Module._load (electron/js2c/asar.js:717:26)
> > at Function.Module._load (electron/js2c/asar.js:717:26)
> > at Module.require (internal/modules/cjs/loader.js:853:19)
> > at require (internal/modules/cjs/helpers.js:74:18)
> > at Object. (D:\Donnees\Desktop\electron-projet\node_modules\custom-electron-titlebar\lib\common\dom.js:7:17)

Could you please share a snippet of what you have done?

You must have put it in the main process. The main process does not have access to the navigator object.

If your folder structure is something like this:
pages
   index.html
   login
      index.html
scripts
   index.js
   ...
main.js

You should put
const customTitlebar = require('custom-electron-titlebar');
in scripts/index.js or in a script tag in pages/index.html.

**Comment by AlexTorresSk** [comment]
Closed due to no response received
