### ISSUE TITLE
css not loading for titlebar

### ISSUE THREAD

**Issue by sphhax** [AlexTorresSk/custom-electron-titlebar#75]
I am using JS. I copied everything from the example and it is still not functioning correctly.
index.html

![image](https://user-images.githubusercontent.com/25424125/75268574-4833a100-57bd-11ea-9350-73cc78deb022.png)

preload.js

![image](https://user-images.githubusercontent.com/25424125/75268608-52559f80-57bd-11ea-85c5-4f149814f612.png)

When running:

![image](https://user-images.githubusercontent.com/25424125/75268484-29cda580-57bd-11ea-8f96-07bbc866dc48.png)

**Comment by AlexTorresSk** [comment]
Are you sure you copied the code from the sample folder?

The preload.js file is not loaded into the index.html file.

**Comment by AlexTorresSk** [comment]
Closed because no response is obtained and is noted that you are placing the preload.js file in a non-corresponding site.
