### ISSUE TITLE
Often get 'Registering disposable on object that has already been disposed.' waring

### ISSUE THREAD

**Issue by iusfof** [AlexTorresSk/custom-electron-titlebar#78]
We use this on windows app and often get waring `Registering disposable on object that has already been disposed.`

We can't understand how to fix it. What can be reason?

**Expected behaviour**
Will be great to fix our (or lib) code to avoid this warnings

**Screenshots**
I'm not sure that it will be useful, but here is a screenshot
![Screenshot 2020-03-17 at 09 11 50](https://user-images.githubusercontent.com/8082727/76827258-75f58e00-682f-11ea-9862-3e6a2167d303.png)

**Desktop\:**
 - OS: Windows
 - electron: 7.1.2
 - custom-electron-titlebar: ^3.1.0

**Comment by AlexTorresSk** [comment]
What are the steps to follow to display this warning?

**Comment by AlexTorresSk** [comment]
Closed due to no _response_ and since it is a **warning**.
