### ISSUE TITLE
Custom titlebar doesn't appear when using electron nightly

### ISSUE THREAD

**Issue by davwheat** [AlexTorresSk/custom-electron-titlebar#81]
**Describe the bug**
No custom titlebar appears when using `electron-nightly` instead of `electron`.

**To Reproduce**
1. Run `npm uninstall electron`
2. Run `npm i electron-nightly`
3. Start your electron project
4. No titlebar!

**Expected behavior**
Well... there should be a titlebar!

**Screenshots**

With Electron 8 (stable):
![image](https://user-images.githubusercontent.com/7406822/79078404-08d6fa80-7d00-11ea-9841-d1b2b4509cd0.png)

With Electron 10 (nightly):
![image](https://user-images.githubusercontent.com/7406822/79078452-69fece00-7d00-11ea-9c34-63eea8a600fa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Electron version: `10.0.0-nightly.20200408`
 - Node Version: `12.14.0`

**Comment by davwheat** [comment]
This is because the `remote` module is disabled by default from Electron 10+ and will be removed in the future.

**Comment by AlexTorresSk** [comment]
This project is made for use with electron, not with electron-nightly

**Comment by davwheat** [comment]
Nightly will become stable soon but ok. Whatever floats your boat.
