### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined at Menubar.setupMenubar

### ISSUE THREAD

**Issue by moganarangan** [AlexTorresSk/custom-electron-titlebar#82]
> Uncaught TypeError: Cannot read property 'forEach' of undefined
>     at Menubar.setupMenubar (C:\proj\some-app\node_modules\custom-electron-titlebar\lib\menubar.js:115)
>     at Titlebar.updateMenu (C:\proj\some-app\node_modules\custom-electron-titlebar\lib\titlebar.js:372)
>     at (index):26

> myTitleBar.updateMenu([]);

"custom-electron-titlebar": "^3.2.2-hotfix62"
"electron": "^8.2.3"

For my requirement, I don't need to show the menu items at all. 

Introduce a property or method to just hide the menu itmes.
Or have a validation inside the `Menubar.setupMenubar` method and  check for `undefined` or `null` before this line 186: `topLevelMenus.forEach((menubarMenu)`
File: `src/menubar.ts`

Or is there a way already to hide the menu bar please let me know.

**Comment by moganarangan** [comment]
Anyone have update on this please...

**Comment by AlexTorresSk** [comment]
Hi @moganarangan 

If you want to delete the menu, all you have to do is defined as null in the construction of the title bar

```
 new customTitlebar.Titlebar({
    backgroundColor: customTitlebar.Color.fromHex('#2f3241'),
    icon: url.format(path.join(__dirname, '/images', '/icon.png')),
    menu: null // This hide the menu
  });
```
