### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by KylaBendrik** [AlexTorresSk/custom-electron-titlebar#86]
**Describe the bug**
When I import custom-electron-titlebar, I get an `Uncaught ReferenceError: require is not defined` error in devtools.

|> Uncaught ReferenceError: require is not defined ------------ external "electron":1
  at Object.electron (external "electron":1)
  at __webpack_require__ (bootstrap:789)
  at fn (bootstrap:100)
  at Object../node/modules/custom-electron-titlebar/lib/menubar.js (menubar.js:12)
  at __webpack_require__ (bootstrap:789)
  at fn (bootstrap:100)
  at Object../node/modules/custom-electron-titlebar/lib/titlebar.js (titlebar.js:15)
  at __webpack_require__ (bootstrap:789)
  at fn (bootstrap:100) 
  at Object../node/modules/custom-electron-titlebar/lib/index.js (index.js:15)

**To Reproduce**
_I've commited a few different options on my project, so you can see exactly what I'm adding and where. (sorry, even the "working" version is ugly, debugging, JSON.stringify stuff)_

[Here's the commit that's currently working properly. ](https://github.com/KylaBendrik/Village-Sim/commit/8f25400be3b9c7b89ac1d26fd1cdf03a65fcbc63)
[Here's the commit with import](https://github.com/KylaBendrik/Village-Sim/commit/9411b5c55330c52757f4672cc4d6cc5ae2eaa075) { Titlebar, Color } from 'custom-electron-titlebar' added to renderer.js

**Expected behavior**
I expected these lines to add a  custom title bar.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Electron version [8.0.0]
 - Node Version [v12.15.0]

**Comment by GypsyDangerous** [comment]
try `window.require`

**Comment by Bilall-RH** [comment]
Hey!
just go to the main.js and add 
`webPreferences: {
        nodeIntegration: true
    }`
in the create window function like that 
`function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({
    width: 600, 
    height: 600,
    backgroundColor: '#ffffff',
    frame: false,
    backgroundColor: '#FFF',
    webPreferences: {
        nodeIntegration: true
    }
  })`

**Comment by Fraasi** [comment]
Electron is patching up some security holes and nodeintegration is no longer recommended. I got around this require/import problem by initiating titlebar in my *preload script* , works nicely in my use case.
see [this](https://stackoverflow.com/questions/57807459/how-to-use-preload-js-properly-in-electron) and [this](https://www.electronjs.org/docs/tutorial/context-isolation) for more info.
```js
const { Titlebar } = require('custom-electron-titlebar');

window.addEventListener('DOMContentLoaded', () => {
  new Titlebar({
    //  settings...
  })
})
```

**Comment by timlg07** [comment]
Using a preload script is the better choice in this case. To see how this can be done, have a look at the [example provided in this repository](https://github.com/AlexTorresSk/custom-electron-titlebar/tree/master/example).

Imo an explanation of this nodeintegration problem should be added to the usage information in the readme file as well.

**Comment by Fraasi** [comment]
@timlg07  yeah, update on the docs would be great.

**Comment by Pritep** [comment]
The problem is the Isolation context must be false, this is the basic configuration:

 ```javascript
const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: false,
    webPreferences: {
      enableRemoteModule: true,
      nodeIntegration: true,
      contextIsolation: false // <== for the bar to work it has to be false
    }
  })
```
