### ISSUE TITLE
Titlebar is slightly blurry

### ISSUE THREAD

**Issue by Heath123** [AlexTorresSk/custom-electron-titlebar#87]
**Describe the bug**
The pixels don't seem to be aligned properly on the title bar, making it look blurry. This might seem like a really small thing, but it makes it look a bit off, and its very noticable to me.

**To Reproduce**
1. Use the library

**Expected behavior**
It should be sharp and pixel-perfect.

**Screenshots**
This library:
![image](https://user-images.githubusercontent.com/13787163/81734042-d6e5bf00-948a-11ea-8602-ca176ae0b2b6.png)
Native:
![image](https://user-images.githubusercontent.com/13787163/81734117-eebd4300-948a-11ea-9346-0f8ea705b027.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Electron version 8.2.5
 - Node Version 12.13.0

**Comment by BB-19** [comment]
I noticed this issue aswell. It seems to be fixed with Electron 9.0.0 for some reason 👍

**Comment by Heath123** [comment]
If anyone needs something without this issue then there's this:
https://github.com/binaryfunt/electron-seamless-titlebar-tutorial
