### ISSUE TITLE
Does "updateMenu" need "setApplicationMenu"?

### ISSUE THREAD

**Issue by chankane** [AlexTorresSk/custom-electron-titlebar#88]
---
name: Does "updateMenu" need "setApplicationMenu"?
about: 
title: 'Does "updateMenu" need "setApplicationMenu"?'
labels: 'question'
assignees: ''

---

**Describe the bug**
I put the following line at the end of the renderer script.

```
titleBar.updateMenu(menu)
```

However, all of the shortcut keys did not work correctly.
These shortcut keys ware default binds.

In addition, it worked fine if I wrote the following. 
```
titleBar.updateMenu(menu)
remote.Menu.setApplicationMenu(menu) // Added this line.
```
Is this a specification?

**Expected behavior**
Just put `` updateMenu`` to work correctly.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Electron version [v9.0.0]
 - Node Version [v12.16.3]

Sorry.
I am not native and not good at English.

**Comment by yy923683900** [comment]
same problem

**Comment by ericblade** [comment]
My guess would be that this could be done automatically in the lib, assuming that there's no reason you would want this lib's menu to be different from the true application menu.
