### ISSUE TITLE
VSCode?

### ISSUE THREAD

**Issue by leontepe** [AlexTorresSk/custom-electron-titlebar#89]
Is this in any way based on the VSCode source or does VSCode even use this package?

**Comment by ivanjeremic** [comment]
Far as I know it is totally custom and not the same as VSCode titlebar.

**Comment by janvorisek** [comment]
You could probably extract the titlebar from VS Code Git repository.

**Comment by AlexTorresSk** [comment]
This is based on the VSCode titlebar
