### ISSUE TITLE
App content not dispalyed

### ISSUE THREAD

**Issue by appu-sm** [AlexTorresSk/custom-electron-titlebar#94]
**Describe the bug**
The Electron's app content is not displayed, we can see only grey window without any console errors, and also the frame is also not working

**To Reproduce**
1)disabled frame in browser window option
2) loaded the preload script
3) enabled node integration
4) added the render script in script tags in html inside the body tag

**Expected behavior**
the custom frame window along with the app's content should be displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/26466494/87161878-095e3d80-c2bd-11ea-8b57-60a1e0c82932.png)

**Desktop (please complete the following information):**
 - OS:  win 10
 - Electron version: 9.0.5

**Comment by AlexTorresSk** [comment]
You can provide the code snippet where you placed the title bar
