### ISSUE TITLE
Titlebar action buttons not displayed

### ISSUE THREAD

**Issue by anandsiddharth** [AlexTorresSk/custom-electron-titlebar#95]
**Description**
The action buttons on titlebar are not getting displayed
```javascript
 new Titlebar({
      shadow: true,
      backgroundColor: Color.fromHex("#1b1a1a"),

      maximizable: true,
      closeable: true,
      drag: true,
   });
```

<img width="1211" alt="Screenshot 2020-07-17 at 5 16 41 AM" src="https://user-images.githubusercontent.com/6649533/87733199-b6204980-c7ec-11ea-8204-0f6d1c685e02.png">

**System**
 - OS: [Mac OS Catalina ]
 - Electron version [^4.0.5]
 - Node Version [v10.15.1]

**Comment by ArcherGu** [comment]
you can add this setting: 
`titleBarStyle: 'hidden'`
Reference: https://electronjs.org/docs/api/frameless-window#alternatives-on-macos

**Comment by anandsiddharth** [comment]
It worked great thankyou
