### ISSUE TITLE
Cannot read property 'firstChild' of null at Titlebar.createTitlebar

### ISSUE THREAD

**Issue by shinuvs** [AlexTorresSk/custom-electron-titlebar#98]
**Cannot create the titlebar it is getting error**
Cannot read property 'firstChild' of null at Titlebar.createTitlebar

**To Reproduce**
<head>
    <meta charset = "UTF-8">
    <title>Home</title>
    <script src="./home.js"></script>
    <link rel="stylesheet" type="text/css" href="./home.css">
    <script>
        const customTitlebar = require('custom-electron-titlebar');
        new customTitlebar.Titlebar({
            backgroundColor: customTitlebar.Color.fromHex('#444')
        });
    </script>
</head>

**Desktop (please complete the following information):**
 - OS:  Windows
 - Electron version 9.1.0
 - Node Version 13.11.0

**Comment by AlexTorresSk** [comment]
You must add cet (custom-electron-titlebar) to your preload.js file
